'use client';

import { motion } from '@/components/providers';
import { FileText, UserCheck, Ban, Scale, RefreshCw, AlertTriangle, Mail } from 'lucide-react';

const LAST_UPDATED = 'June 3, 2026';

const SECTIONS = [
  {
    id: 'acceptance',
    icon: UserCheck,
    number: '01',
    title: 'Acceptance of Terms',
    color: 'text-blue-600',
    bg: 'bg-blue-50',
    paras: [
      'By creating an account or using Coin-IQ in any capacity, you agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree with any part of these terms, you must not use the platform.',
      'We reserve the right to update these terms at any time. Continued use of the platform after changes are posted constitutes acceptance of the revised terms. Material changes will be communicated via email to registered users.',
    ],
  },
  {
    id: 'use-of-service',
    icon: FileText,
    number: '02',
    title: 'Use of the Service',
    color: 'text-violet-600',
    bg: 'bg-violet-50',
    paras: [
      'Coin-IQ provides AI-generated cryptocurrency price direction predictions, market analytics, news aggregation, and educational content. The platform is intended for informational and educational purposes only.',
      'You must be at least 18 years of age to create an account. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.',
      'You agree to provide accurate registration information and to keep it up to date. You may not create accounts for other people without their permission or operate multiple accounts for deceptive purposes.',
    ],
  },
  {
    id: 'prohibited',
    icon: Ban,
    number: '03',
    title: 'Prohibited Conduct',
    color: 'text-rose-600',
    bg: 'bg-rose-50',
    paras: [
      'You may not use Coin-IQ to engage in any activity that violates applicable laws or regulations, including securities laws in your jurisdiction.',
    ],
    bullets: [
      'Scraping, crawling, or systematically extracting prediction data via automated means without prior written permission',
      'Reverse engineering, decompiling, or attempting to extract source code from our ML models or backend systems',
      'Sharing account credentials or reselling access to premium features',
      'Uploading malicious code, attempting to gain unauthorised access, or interfering with platform infrastructure',
      'Misrepresenting Coin-IQ predictions as financial advice to other people',
      'Circumventing rate limits, authentication mechanisms, or any security feature',
    ],
  },
  {
    id: 'intellectual-property',
    icon: Scale,
    number: '04',
    title: 'Intellectual Property',
    color: 'text-amber-600',
    bg: 'bg-amber-50',
    paras: [
      'All content on Coin-IQ — including but not limited to ML model architecture, prediction algorithms, course content, UI designs, and written materials — is the exclusive intellectual property of Coin-IQ and its team.',
      'You are granted a limited, non-exclusive, non-transferable licence to access and use the platform for personal, non-commercial purposes. This licence does not include the right to reproduce, distribute, or create derivative works.',
      'User-generated content (such as profile information) remains your property. By submitting it, you grant us a non-exclusive licence to use it for service delivery purposes.',
    ],
  },
  {
    id: 'disclaimers',
    icon: AlertTriangle,
    number: '05',
    title: 'Disclaimers & Liability',
    color: 'text-orange-600',
    bg: 'bg-orange-50',
    paras: [
      'THE PLATFORM IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF HARMFUL COMPONENTS.',
      'COIN-IQ DOES NOT PROVIDE FINANCIAL, INVESTMENT, LEGAL, OR TAX ADVICE. ALL PREDICTIONS ARE GENERATED BY MACHINE LEARNING MODELS AND REPRESENT PROBABILISTIC ESTIMATES ONLY. PAST MODEL PERFORMANCE DOES NOT GUARANTEE FUTURE RESULTS.',
      'TO THE MAXIMUM EXTENT PERMITTED BY LAW, COIN-IQ AND ITS TEAM SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF — OR INABILITY TO USE — THE PLATFORM.',
    ],
  },
  {
    id: 'termination',
    icon: RefreshCw,
    number: '06',
    title: 'Termination',
    color: 'text-gray-600',
    bg: 'bg-gray-100',
    paras: [
      'You may terminate your account at any time by contacting us. We may suspend or terminate your access immediately, without prior notice, for conduct that we believe violates these Terms of Service or is harmful to other users, third parties, or us.',
      'Upon termination, your right to use the platform ceases immediately. Provisions of these terms that by their nature should survive termination shall survive, including intellectual property rights, disclaimers, and limitations of liability.',
    ],
  },
];

export default function TermsPage() {
  return (
    <div className="bg-white">
      {/* Hero */}
      <section className="border-b border-gray-100 py-20 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto">
          <motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
            <div className="flex items-center gap-3 mb-6">
              <div className="w-12 h-12 bg-gray-900 rounded-2xl flex items-center justify-center">
                <FileText className="w-6 h-6 text-white" />
              </div>
              <div>
                <p className="text-xs font-semibold text-gray-400 uppercase tracking-widest">Legal</p>
                <h1 className="text-2xl font-black text-gray-900 leading-none">Terms of Service</h1>
              </div>
            </div>
            <p className="text-gray-500 text-lg leading-relaxed max-w-2xl">
              Please read these terms carefully before using Coin-IQ. They govern your use of the platform and outline our mutual obligations.
            </p>
            <div className="flex items-center gap-4 mt-6">
              <span className="flex items-center gap-1.5 text-xs text-gray-400">
                <RefreshCw className="w-3.5 h-3.5" /> Last updated: {LAST_UPDATED}
              </span>
              <span className="text-gray-200">|</span>
              <span className="text-xs text-gray-500">Effective immediately upon account creation</span>
            </div>
          </motion.div>
        </div>
      </section>

      {/* TOC */}
      <section className="py-10 px-4 sm:px-6 lg:px-8 bg-gray-50 border-b border-gray-100">
        <div className="max-w-4xl mx-auto">
          <p className="text-xs font-semibold text-gray-400 uppercase tracking-widest mb-5">Contents</p>
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
            {SECTIONS.map(s => (
              <a key={s.id} href={`#${s.id}`}
                className="flex items-center gap-2 px-3 py-2.5 bg-white border border-gray-200 rounded-xl text-xs font-semibold text-gray-600 hover:text-gray-900 hover:border-gray-300 hover:shadow-sm transition-all">
                <span className="text-[10px] font-black text-gray-300">{s.number}</span>
                {s.title}
              </a>
            ))}
          </div>
        </div>
      </section>

      {/* Content */}
      <section className="py-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto space-y-14">
          {SECTIONS.map((s, si) => (
            <motion.div key={s.id} id={s.id}
              initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }} transition={{ delay: si * 0.05 }}>
              <div className="flex items-center gap-3 mb-6">
                <div className={`w-9 h-9 rounded-xl flex items-center justify-center shrink-0 ${s.bg}`}>
                  <s.icon className={`w-4.5 h-4.5 ${s.color}`} />
                </div>
                <div className="flex items-baseline gap-2">
                  <span className="text-xs font-black text-gray-300">{s.number}</span>
                  <h2 className="text-xl font-black text-gray-900">{s.title}</h2>
                </div>
              </div>
              <div className="pl-12 space-y-4">
                {s.paras.map((p, pi) => (
                  <p key={pi} className={`text-sm leading-relaxed ${p === p.toUpperCase() && p.length > 40 ? 'text-gray-500 bg-gray-50 border border-gray-200 rounded-xl p-4 font-medium' : 'text-gray-600'}`}>
                    {p}
                  </p>
                ))}
                {s.bullets && (
                  <ul className="space-y-2.5 mt-2">
                    {s.bullets.map((b, bi) => (
                      <li key={bi} className="flex items-start gap-2.5 text-sm text-gray-600">
                        <span className="w-1.5 h-1.5 rounded-full bg-gray-400 mt-2 shrink-0" />
                        {b}
                      </li>
                    ))}
                  </ul>
                )}
              </div>
            </motion.div>
          ))}

          {/* Contact */}
          <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}
            className="bg-gray-950 text-white rounded-2xl p-8">
            <div className="flex items-start gap-4">
              <div className="w-10 h-10 bg-white/10 rounded-xl flex items-center justify-center shrink-0">
                <Mail className="w-5 h-5 text-white" />
              </div>
              <div>
                <h3 className="font-black text-lg mb-2">Questions about these terms?</h3>
                <p className="text-gray-400 text-sm leading-relaxed mb-4">
                  If you have any questions about these Terms of Service, please contact us before using the platform.
                </p>
                <a href="mailto:legal@coin-iq.app"
                  className="inline-flex items-center gap-2 px-5 py-2.5 bg-white text-gray-900 text-sm font-bold rounded-xl hover:bg-gray-100 transition-colors">
                  legal@coin-iq.app
                </a>
              </div>
            </div>
          </motion.div>
        </div>
      </section>
    </div>
  );
}
